/*!
 * 
 * [Dojo](https://dojo.io/)
 * Copyright [JS Foundation](https://js.foundation/) & contributors
 * [New BSD license](https://github.com/dojo/meta/blob/master/LICENSE)
 * All rights reserved
 * 
 */
(window.dojoWebpackJsonpdojo_widgets_custom_elements=window.dojoWebpackJsonpdojo_widgets_custom_elements||[]).push([[32,42],{112:function(e,o,t){e.exports={" _key":"@dojo/widgets/context-popup",trigger:"context-popup-m__trigger__3A_JZ"}},26:function(e,o,t){"use strict";t.r(o),t.d(o,"Popup",function(){return l});var n=t(84),r=t(75),s=t(85),c=t(5),i=t(86),p=t(87);const l=Object(c.a)({dimensions:n.b,theme:r.b,bodyScroll:s.a}).properties().children()(function({properties:e,children:o,middleware:{dimensions:t,theme:n,bodyScroll:r}}){const{underlayVisible:s=!1,position:l="below",x:u,yBottom:d,yTop:a,onClose:m,open:y}=e(),g=t.get("wrapper"),b=document.documentElement.scrollTop+document.documentElement.clientHeight,_=document.documentElement.scrollTop,f=a+g.size.height<=b,h=d-g.size.height>=_;let w={opacity:"0"};g.size.height&&(w={left:`${u}px`,opacity:"1"},"below"===l?w.top=f?`${a}px`:`${d-g.size.height}px`:"above"===l&&(w.top=h?`${d-g.size.height}px`:`${a}px`));const v=n.classes(i);return r(!y),y&&Object(c.m)("body",null,Object(c.m)("div",{key:"underlay",classes:[n.variant(),p.underlay,s&&v.underlayVisible],onclick:m}),Object(c.m)("div",{key:"wrapper",classes:[n.variant(),p.root],styles:w},o()))});o.default=l},34:function(e,o,t){"use strict";t.r(o),t.d(o,"ContextPopup",function(){return u});var n=t(5),r=t(79),s=t(26),c=t(77),i=t(112);const p=Object(c.a)(),l=Object(n.a)({icache:p,focus:r.a}).properties().children(),u=l(function({properties:e,children:o,middleware:{icache:t,focus:r}}){const c=t.getOrSet("x",0),p=t.getOrSet("y",0),{trigger:l,content:u}=o()[0],d=()=>{const{onClose:o}=e();t.set("open",!1),o&&o()};return Object(n.m)("virtual",null,Object(n.m)("div",{classes:i.trigger,key:"trigger",oncontextmenu:o=>{const{onOpen:n}=e();o.preventDefault(),r.focus(),t.set("x",o.pageX-2),t.set("y",o.pageY-4),t.set("open",!0),n&&n()}},l),Object(n.m)(s.default,{key:"popup",x:c,yTop:p,yBottom:document.documentElement.scrollTop+document.documentElement.clientHeight,onClose:d,position:"below",open:t.get("open")},Object(n.m)("div",null,u({close:d,shouldFocus:r.shouldFocus}))))});o.default=u},85:function(e,o,t){"use strict";t.d(o,"a",function(){return i});var n=t(5),r=t(0);const s=Object(n.a)({destroy:n.c}),c=r.a.document.body.style,i=s(function({middleware:{destroy:e}}){let o=!1,t=void 0;const n=()=>{o&&(t?c.setProperty("overflow",t):c.removeProperty("overflow"),o=!1,t=void 0)};return e(()=>{o&&n()}),e=>{e?n():o||(o=!0,t=c.getPropertyValue("overflow"),c.setProperty("overflow","hidden"))}});o.b=i},86:function(e,o,t){e.exports={" _key":"@dojo/widgets/popup",underlayVisible:"popup-m__underlayVisible__1Cxv3"}},87:function(e,o,t){e.exports={" _key":"@dojo/widgets/popup",root:"popup-m__root__3WJlO",underlay:"popup-m__underlay__2CC_p"}}}]);
//# sourceMappingURL=32-7.0.0-pre.js.map