/*!
 * 
 * [Dojo](https://dojo.io/)
 * Copyright [JS Foundation](https://js.foundation/) & contributors
 * [New BSD license](https://github.com/dojo/meta/blob/master/LICENSE)
 * All rights reserved
 * 
 */
(window.dojoWebpackJsonpdojo_widgets_custom_elements=window.dojoWebpackJsonpdojo_widgets_custom_elements||[]).push([[33,42],{26:function(e,t,o){"use strict";o.r(t),o.d(t,"Popup",function(){return d});var n=o(84),r=o(75),i=o(85),s=o(5),p=o(86),c=o(87);const d=Object(s.a)({dimensions:n.b,theme:r.b,bodyScroll:i.a}).properties().children()(function({properties:e,children:t,middleware:{dimensions:o,theme:n,bodyScroll:r}}){const{underlayVisible:i=!1,position:d="below",x:l,yBottom:u,yTop:a,onClose:m,open:g}=e(),y=o.get("wrapper"),b=document.documentElement.scrollTop+document.documentElement.clientHeight,h=document.documentElement.scrollTop,_=a+y.size.height<=b,w=u-y.size.height>=h;let f={opacity:"0"};y.size.height&&(f={left:`${l}px`,opacity:"1"},"below"===d?f.top=_?`${a}px`:`${u-y.size.height}px`:"above"===d&&(f.top=w?`${u-y.size.height}px`:`${a}px`));const j=n.classes(p);return r(!g),g&&Object(s.m)("body",null,Object(s.m)("div",{key:"underlay",classes:[n.variant(),c.underlay,i&&j.underlayVisible],onclick:m}),Object(s.m)("div",{key:"wrapper",classes:[n.variant(),c.root],styles:f},t()))});t.default=d},28:function(e,t,o){"use strict";o.r(t),o.d(t,"TriggerPopup",function(){return l});var n=o(83),r=o(84),i=o(5),s=o(26),p=o(96),c=o(77);const d=Object(c.a)(),l=Object(i.a)({dimensions:r.b,icache:d}).properties().children()(function({properties:e,children:t,middleware:{dimensions:o,icache:r}}){const c=e(),{matchWidth:d=!0,onOpen:l}=c,u=n.d(c,["matchWidth","onOpen"]),{position:a,size:m}=o.get("trigger"),g=a.top+document.documentElement.scrollTop,y=g+m.height,b={width:d?`${m.width}px`:"auto"},{trigger:h,content:_}=t()[0],w=()=>{const{onClose:t}=e();r.set("open",!1),t&&t()};return Object(i.m)("virtual",null,Object(i.m)("span",{key:"trigger",classes:p.trigger},h(()=>{const{onOpen:t}=e();r.set("open",!r.get("open")),t&&t()})),Object(i.m)(s.default,Object.assign({key:"popup"},u,{x:a.left,yTop:y,yBottom:g,onClose:w,open:r.get("open")}),Object(i.m)("div",{key:"trigger-wrapper",styles:b},_(w))))});t.default=l},85:function(e,t,o){"use strict";o.d(t,"a",function(){return p});var n=o(5),r=o(0);const i=Object(n.a)({destroy:n.c}),s=r.a.document.body.style,p=i(function({middleware:{destroy:e}}){let t=!1,o=void 0;const n=()=>{t&&(o?s.setProperty("overflow",o):s.removeProperty("overflow"),t=!1,o=void 0)};return e(()=>{t&&n()}),e=>{e?n():t||(t=!0,o=s.getPropertyValue("overflow"),s.setProperty("overflow","hidden"))}});t.b=p},86:function(e,t,o){e.exports={" _key":"@dojo/widgets/popup",underlayVisible:"popup-m__underlayVisible__1Cxv3"}},87:function(e,t,o){e.exports={" _key":"@dojo/widgets/popup",root:"popup-m__root__3WJlO",underlay:"popup-m__underlay__2CC_p"}},96:function(e,t,o){e.exports={" _key":"@dojo/widgets/trigger-popup",trigger:"trigger-popup-m__trigger__2isxr"}}}]);
//# sourceMappingURL=33-7.0.0-pre.js.map