/*!
 * 
 * [Dojo](https://dojo.io/)
 * Copyright [JS Foundation](https://js.foundation/) & contributors
 * [New BSD license](https://github.com/dojo/meta/blob/master/LICENSE)
 * All rights reserved
 * 
 */
(window.dojoWebpackJsonpdojo_widgets_custom_elements=window.dojoWebpackJsonpdojo_widgets_custom_elements||[]).push([[36],{178:function(e,t,n){e.exports={" _key":"@dojo/widgets/three-column-layout",root:"three-column-layout-m__root__31HFf",center:"three-column-layout-m__center__3u6bV"}},179:function(e,t,n){e.exports={" _key":"@dojo/widgets/three-column-layout",root:"three-column-layout-m__root__Io1yp",leading:"three-column-layout-m__leading__cWlTV",center:"three-column-layout-m__center__2PvVq",trailing:"three-column-layout-m__trailing__hs2u9"}},62:function(e,t,n){"use strict";n.r(t),n.d(t,"ThreeColumnLayout",function(){return l});var r=n(5),o=n(121),i=n(73),s=n(178),a=n(76),c=n(179);const l=Object(r.a)({breakpoint:o.a,theme:i.a}).properties().children()(function({properties:e,children:t,middleware:{breakpoint:n,theme:o}}){const{twoColumnBreakpoint:i=1024,oneColumnBreakpoint:l=600,bias:u="leading"}=e(),[{leading:d,center:m,trailing:_}]=t(),h=o.classes(c),{breakpoint:b}=n.get("root",{LARGE:i,MEDIUM:l,SMALL:0})||{breakpoint:"LARGE"},y="SMALL"===b||"MEDIUM"===b&&"trailing"===u,g="SMALL"===b||"MEDIUM"===b&&"leading"===u;return Object(r.m)("div",{key:"root",classes:[o.variant(),s.root,h.root]},Object(r.m)("div",{key:"leading",classes:[h.leading,y&&a.visuallyHidden]},d),Object(r.m)("div",{key:"center",classes:[s.center,h.center]},m),Object(r.m)("div",{key:"trailing",classes:[h.trailing,g&&a.visuallyHidden]},_))});t.default=l},73:function(e,t,n){"use strict";n.d(t,"b",function(){return c});var r=n(5),o=n(75);const i=Object(r.a)({coreTheme:o.a});function s(e){return`${e.charAt(0).toUpperCase()}${e.slice(1)}`}function a(e){return e&&e.hasOwnProperty("variant")}const c=i(function({middleware:{coreTheme:e},properties:t}){return Object.assign({compose:(n,r,o)=>{const i=t().theme,c=n[" _key"],l=r[" _key"],u=Object.keys(n).reduce((e,t)=>" _key"===t?e:(o&&!e[`${o}${s(t)}`]&&(e[`${o}${s(t)}`]=" "),r[t]||(e[t]=" "),e),{" _key":l}),d=e.classes(u),m=e.classes(r);let _=e.classes(n);if(o){const e=Object.keys(Object.assign({},d,m)).reduce((e,t)=>{if(0===t.indexOf(o)&&t!==o){const n=function(e){return`${e.charAt(0).toLowerCase()}${e.slice(1)}`}(t.replace(o,""));!m[t]&&d[t]&&d[t].trim()&&(e[n]=`${_[n]} ${d[t].trim()}`),m[t]&&(e[n]=m[t])}return e},{});return _=Object.assign({},_,e),a(i)?{theme:{theme:Object.assign({},i.theme.theme,{[c]:_}),variants:i.theme.variants},variant:i.variant}:Object.assign({},i,{[c]:_})}const h=Object.keys(_).reduce((e,t)=>{if(" _key"===t)return e;const n=m[t]&&m[t].trim();return m[t]?e[t]=n:d[t]&&d[t].trim()&&(e[t]=`${e[t]} ${d[t].trim()}`),e},Object.assign({},_));return a(i)?{theme:{theme:Object.assign({},i.theme.theme,{[c]:h}),variants:i.theme.variants},variant:i.variant}:Object.assign({},i,{[c]:h})}},e)});t.a=c},76:function(e,t,n){e.exports={" _key":"@dojo/widgets/base",visuallyHidden:"base-m__visuallyHidden__1AeWe",focusable:"base-m__focusable__1_qAN",hidden:"base-m__hidden__3QddU"}}}]);
//# sourceMappingURL=36-7.0.0-pre.js.map