/*!
 * 
 * [Dojo](https://dojo.io/)
 * Copyright [JS Foundation](https://js.foundation/) & contributors
 * [New BSD license](https://github.com/dojo/meta/blob/master/LICENSE)
 * All rights reserved
 * 
 */
(window.dojoWebpackJsonpdojo_widgets_custom_elements=window.dojoWebpackJsonpdojo_widgets_custom_elements||[]).push([[37],{183:function(e,t,n){e.exports={" _key":"@dojo/widgets/two-column-layout",root:"two-column-layout-m__root__zozns",even:"two-column-layout-m__even___7Ecz",biased:"two-column-layout-m__biased__2UbH4"}},184:function(e,t,n){e.exports={" _key":"@dojo/widgets/two-column-layout",root:"two-column-layout-m__root__3tIsG",column:"two-column-layout-m__column__AIyn8",small:"two-column-layout-m__small__3zUZI"}},64:function(e,t,n){"use strict";n.r(t),n.d(t,"TwoColumnLayout",function(){return l});var o=n(5),s=n(73),i=n(183),a=n(184),r=n(76),c=n(121);const l=Object(o.a)({theme:s.a,breakpoint:c.a}).properties().children()(function({properties:e,children:t,middleware:{theme:n,breakpoint:s}}){const{bias:c,breakpoint:l=600}=e(),{breakpoint:u}=s.get("root",{SMALL:0,LARGE:l})||{breakpoint:"LARGE"},d="SMALL"===u,m=n.classes(a),{leading:_,trailing:b}=t()[0];return Object(o.m)("div",{key:"root",classes:[n.variant(),i.root,m.root]},Object(o.m)("div",{key:"leading",classes:["leading"===c&&i.biased,void 0===c&&!d&&i.even,"trailing"===c&&d&&r.visuallyHidden,"trailing"===c&&!d&&m.small,m.column]},_),Object(o.m)("div",{key:"trailing",classes:["trailing"===c&&i.biased,void 0===c&&!d&&i.even,("leading"===c||void 0===c)&&d&&r.visuallyHidden,"leading"===c&&!d&&m.small,m.column]},b))});t.default=l},73:function(e,t,n){"use strict";n.d(t,"b",function(){return c});var o=n(5),s=n(75);const i=Object(o.a)({coreTheme:s.a});function a(e){return`${e.charAt(0).toUpperCase()}${e.slice(1)}`}function r(e){return e&&e.hasOwnProperty("variant")}const c=i(function({middleware:{coreTheme:e},properties:t}){return Object.assign({compose:(n,o,s)=>{const i=t().theme,c=n[" _key"],l=o[" _key"],u=Object.keys(n).reduce((e,t)=>" _key"===t?e:(s&&!e[`${s}${a(t)}`]&&(e[`${s}${a(t)}`]=" "),o[t]||(e[t]=" "),e),{" _key":l}),d=e.classes(u),m=e.classes(o);let _=e.classes(n);if(s){const e=Object.keys(Object.assign({},d,m)).reduce((e,t)=>{if(0===t.indexOf(s)&&t!==s){const n=function(e){return`${e.charAt(0).toLowerCase()}${e.slice(1)}`}(t.replace(s,""));!m[t]&&d[t]&&d[t].trim()&&(e[n]=`${_[n]} ${d[t].trim()}`),m[t]&&(e[n]=m[t])}return e},{});return _=Object.assign({},_,e),r(i)?{theme:{theme:Object.assign({},i.theme.theme,{[c]:_}),variants:i.theme.variants},variant:i.variant}:Object.assign({},i,{[c]:_})}const b=Object.keys(_).reduce((e,t)=>{if(" _key"===t)return e;const n=m[t]&&m[t].trim();return m[t]?e[t]=n:d[t]&&d[t].trim()&&(e[t]=`${e[t]} ${d[t].trim()}`),e},Object.assign({},_));return r(i)?{theme:{theme:Object.assign({},i.theme.theme,{[c]:b}),variants:i.theme.variants},variant:i.variant}:Object.assign({},i,{[c]:b})}},e)});t.a=c},76:function(e,t,n){e.exports={" _key":"@dojo/widgets/base",visuallyHidden:"base-m__visuallyHidden__1AeWe",focusable:"base-m__focusable__1_qAN",hidden:"base-m__hidden__3QddU"}}}]);
//# sourceMappingURL=37-7.0.0-pre.js.map