/*!
 * 
 * [Dojo](https://dojo.io/)
 * Copyright [JS Foundation](https://js.foundation/) & contributors
 * [New BSD license](https://github.com/dojo/meta/blob/master/LICENSE)
 * All rights reserved
 * 
 */
(window.dojoWebpackJsonpdojo_widgets_custom_elements=window.dojoWebpackJsonpdojo_widgets_custom_elements||[]).push([[45],{164:function(e,t,r){e.exports={" _key":"@dojo/widgets/progress",root:"progress-m__root__2vX10",output:"progress-m__output__1KJw_",bar:"progress-m__bar__1uSqt",progress:"progress-m__progress__3V_Rl"}},53:function(e,t,r){"use strict";r.r(t),r.d(t,"Progress",function(){return c});var s=r(5),n=r(73),a=r(164),o=r(74);const c=Object(s.a)({theme:n.a}).properties().children()(function({children:e,id:t,properties:r,middleware:{theme:n}}){const c=n.classes(a),{aria:i={},value:u,showOutput:m=!0,max:p=100,min:d=0,widgetId:b=`progress-${t}`}=r(),g=Math.round((u-d)/(p-d)*100),_=((t,r)=>{const{output:s}=e()[0]||{};return s?s(t,r):`${r}%`})(u,g);return Object(s.m)("div",{key:"root",classes:[n.variant(),c.root]},Object(s.m)("div",Object.assign({classes:c.bar,role:"progressbar"},Object(o.b)(i),{"aria-valuemin":`${d}`,"aria-valuemax":`${p}`,"aria-valuenow":`${u}`,"aria-valuetext":_,id:b}),(e=>Object(s.m)("div",{classes:c.progress,styles:{width:`${e}%`}}))(g)),m?Object(s.m)("span",{classes:c.output},_):null)});t.default=c},73:function(e,t,r){"use strict";r.d(t,"b",function(){return i});var s=r(5),n=r(75);const a=Object(s.a)({coreTheme:n.a});function o(e){return`${e.charAt(0).toUpperCase()}${e.slice(1)}`}function c(e){return e&&e.hasOwnProperty("variant")}const i=a(function({middleware:{coreTheme:e},properties:t}){return Object.assign({compose:(r,s,n)=>{const a=t().theme,i=r[" _key"],u=s[" _key"],m=Object.keys(r).reduce((e,t)=>" _key"===t?e:(n&&!e[`${n}${o(t)}`]&&(e[`${n}${o(t)}`]=" "),s[t]||(e[t]=" "),e),{" _key":u}),p=e.classes(m),d=e.classes(s);let b=e.classes(r);if(n){const e=Object.keys(Object.assign({},p,d)).reduce((e,t)=>{if(0===t.indexOf(n)&&t!==n){const r=function(e){return`${e.charAt(0).toLowerCase()}${e.slice(1)}`}(t.replace(n,""));!d[t]&&p[t]&&p[t].trim()&&(e[r]=`${b[r]} ${p[t].trim()}`),d[t]&&(e[r]=d[t])}return e},{});return b=Object.assign({},b,e),c(a)?{theme:{theme:Object.assign({},a.theme.theme,{[i]:b}),variants:a.theme.variants},variant:a.variant}:Object.assign({},a,{[i]:b})}const g=Object.keys(b).reduce((e,t)=>{if(" _key"===t)return e;const r=d[t]&&d[t].trim();return d[t]?e[t]=r:p[t]&&p[t].trim()&&(e[t]=`${e[t]} ${p[t].trim()}`),e},Object.assign({},b));return c(a)?{theme:{theme:Object.assign({},a.theme.theme,{[i]:g}),variants:a.theme.variants},variant:a.variant}:Object.assign({},a,{[i]:g})}},e)});t.a=i},74:function(e,t,r){"use strict";var s;function n(e){return Object.keys(e).reduce((t,r)=>(t[`aria-${r.toLowerCase()}`]=e[r],t),{})}r.d(t,"a",function(){return s}),r.d(t,"b",function(){return n}),function(e){e[e.Down=40]="Down",e[e.End=35]="End",e[e.Enter=13]="Enter",e[e.Escape=27]="Escape",e[e.Home=36]="Home",e[e.Left=37]="Left",e[e.PageDown=34]="PageDown",e[e.PageUp=33]="PageUp",e[e.Right=39]="Right",e[e.Space=32]="Space",e[e.Tab=9]="Tab",e[e.Up=38]="Up"}(s||(s={}))}}]);
//# sourceMappingURL=45-7.0.0-pre.js.map