/*!
 * 
 * [Dojo](https://dojo.io/)
 * Copyright [JS Foundation](https://js.foundation/) & contributors
 * [New BSD license](https://github.com/dojo/meta/blob/master/LICENSE)
 * All rights reserved
 * 
 */
(window.dojoWebpackJsonpdojo_widgets_custom_elements=window.dojoWebpackJsonpdojo_widgets_custom_elements||[]).push([[46],{125:function(e,r,t){e.exports={" _key":"@dojo/widgets/breadcrumb-group",root:"breadcrumb-group-m__root__2GLDa",list:"breadcrumb-group-m__list__3mG7R",listItem:"breadcrumb-group-m__listItem__8UkbK",separator:"breadcrumb-group-m__separator__3d16x",breadcrumb:"breadcrumb-group-m__breadcrumb__mUw1o",current:"breadcrumb-group-m__current__2sn-Y"}},126:function(e,r,t){e.exports={" _key":"@dojo/widgets/breadcrumb-group",listFixed:"breadcrumb-group-m__listFixed__sUJba",breadcrumbFixed:"breadcrumb-group-m__breadcrumbFixed__3B1O-",separatorFixed:"breadcrumb-group-m__separatorFixed__2guMR"}},42:function(e,r,t){"use strict";t.r(r),t.d(r,"Separator",function(){return u}),t.d(r,"BreadcrumbSeparator",function(){return u}),t.d(r,"Breadcrumb",function(){return d}),t.d(r,"BreadcrumbGroup",function(){return i});var a=t(75),c=t(5),s=t(125),o=t(126);const u=Object(c.a)({theme:a.a})(function({children:e,middleware:{theme:r}}){const t=r.classes(s);return Object(c.m)("li",{"aria-hidden":"true",classes:t.listItem},Object(c.m)("span",{classes:[o.separatorFixed,t.separator]},e()))}),d=Object(c.a)({theme:a.a}).properties()(function({children:e,middleware:{theme:r},properties:t}){const{current:a,href:u,title:d}=t(),i=r.classes(s);return Object(c.m)("li",{classes:[i.listItem,a?i.current:void 0]},u?Object(c.m)("a",{"aria-current":a||void 0,classes:[o.breadcrumbFixed,i.breadcrumb],href:u,title:d},e()):Object(c.m)("span",{"aria-current":a||void 0,classes:[o.breadcrumbFixed,i.breadcrumb]},e()))}),i=Object(c.a)({theme:a.a}).properties().children()(function({children:e,properties:r,middleware:{theme:t}}){const{items:a,label:i}=r(),b=t.classes(s),m=e=>{const r=e.length-1;return e.map((e,t)=>Object(c.m)("virtual",null,0!==t&&Object(c.m)(u,{key:`breadcrumb-${t}-separator`},"/"),Object(c.m)(d,{key:`breadcrumb-${t}`,current:t===r?"page":void 0,href:e.href,title:e.title},e.label)))},[n=m]=e();return Object(c.m)("nav",{classes:[t.variant(),b.root],"aria-label":i},Object(c.m)("ol",{classes:[o.listFixed,b.list]},n(a)))});r.default=i}}]);
//# sourceMappingURL=46-7.0.0-pre.js.map