/*!
 * 
 * [Dojo](https://dojo.io/)
 * Copyright [JS Foundation](https://js.foundation/) & contributors
 * [New BSD license](https://github.com/dojo/meta/blob/master/LICENSE)
 * All rights reserved
 * 
 */
(window.dojoWebpackJsonpdojo_widgets_custom_elements=window.dojoWebpackJsonpdojo_widgets_custom_elements||[]).push([[47],{124:function(e,a,t){e.exports={" _key":"@dojo/widgets/avatar",root:"avatar-m__root__3K9z0",avatarColorSecondary:"avatar-m__avatarColorSecondary__1482_",avatarColor:"avatar-m__avatarColor__1r5W-",small:"avatar-m__small__2yQZb",medium:"avatar-m__medium__8xlzj",large:"avatar-m__large__2yM2d",circle:"avatar-m__circle__ElfyL",square:"avatar-m__square__37eQa",rounded:"avatar-m__rounded__RpRws"}},41:function(e,a,t){"use strict";t.r(a),t.d(a,"Avatar",function(){return o});var r=t(5),s=t(73),n=t(124);const o=Object(r.a)({theme:s.a}).properties()(function({middleware:{theme:e},properties:a,children:t}){const s=e.classes(n),{secondary:o,src:c,alt:i,variant:_="circle",size:m="medium"}=a();return Object(r.m)("div",{key:"root",role:c&&"image","aria-label":i,classes:[e.variant(),s.root,o?s.avatarColorSecondary:s.avatarColor,s[m],s[_]],styles:c?{backgroundImage:`url(${c})`}:{}},t())});a.default=o},73:function(e,a,t){"use strict";t.d(a,"b",function(){return i});var r=t(5),s=t(75);const n=Object(r.a)({coreTheme:s.a});function o(e){return`${e.charAt(0).toUpperCase()}${e.slice(1)}`}function c(e){return e&&e.hasOwnProperty("variant")}const i=n(function({middleware:{coreTheme:e},properties:a}){return Object.assign({compose:(t,r,s)=>{const n=a().theme,i=t[" _key"],_=r[" _key"],m=Object.keys(t).reduce((e,a)=>" _key"===a?e:(s&&!e[`${s}${o(a)}`]&&(e[`${s}${o(a)}`]=" "),r[a]||(e[a]=" "),e),{" _key":_}),u=e.classes(m),l=e.classes(r);let d=e.classes(t);if(s){const e=Object.keys(Object.assign({},u,l)).reduce((e,a)=>{if(0===a.indexOf(s)&&a!==s){const t=function(e){return`${e.charAt(0).toLowerCase()}${e.slice(1)}`}(a.replace(s,""));!l[a]&&u[a]&&u[a].trim()&&(e[t]=`${d[t]} ${u[a].trim()}`),l[a]&&(e[t]=l[a])}return e},{});return d=Object.assign({},d,e),c(n)?{theme:{theme:Object.assign({},n.theme.theme,{[i]:d}),variants:n.theme.variants},variant:n.variant}:Object.assign({},n,{[i]:d})}const v=Object.keys(d).reduce((e,a)=>{if(" _key"===a)return e;const t=l[a]&&l[a].trim();return l[a]?e[a]=t:u[a]&&u[a].trim()&&(e[a]=`${e[a]} ${u[a].trim()}`),e},Object.assign({},d));return c(n)?{theme:{theme:Object.assign({},n.theme.theme,{[i]:v}),variants:n.theme.variants},variant:n.variant}:Object.assign({},n,{[i]:v})}},e)});a.a=i}}]);
//# sourceMappingURL=47-7.0.0-pre.js.map