/*!
 * 
 * [Dojo](https://dojo.io/)
 * Copyright [JS Foundation](https://js.foundation/) & contributors
 * [New BSD license](https://github.com/dojo/meta/blob/master/LICENSE)
 * All rights reserved
 * 
 */
(window.dojoWebpackJsonpdojo_widgets_custom_elements=window.dojoWebpackJsonpdojo_widgets_custom_elements||[]).push([[49],{156:function(e,t,s){e.exports={" _key":"@dojo/widgets/header",root:"header-m__root__1Wu1d",row:"header-m__row__3e0zv",primary:"header-m__primary__2eL4c",secondary:"header-m__secondary__keWQu",sticky:"header-m__sticky__3Rxub",leading:"header-m__leading__EGBZf",title:"header-m__title__3AvG7",actions:"header-m__actions__3MCfn",action:"header-m__action__1tpKL",trailing:"header-m__trailing__1qern",spacer:"header-m__spacer__3HogK"}},46:function(e,t,s){"use strict";s.r(t),s.d(t,"Header",function(){return c});var r=s(156),a=s(73),i=s(5);const c=Object(i.a)({theme:a.a}).properties().children()(function({children:e,properties:t,middleware:{theme:s}}){const a=s.classes(r),{sticky:c}=t(),{actions:n,leading:o,title:d,trailing:_}=e()[0];return Object(i.m)("header",{key:"header",classes:[s.variant(),c?a.spacer:void 0]},Object(i.m)("div",{classes:[a.root,c&&a.sticky],key:"root"},Object(i.m)("div",{classes:a.row},Object(i.m)("div",{classes:a.primary,key:"primary"},o&&Object(i.m)("div",{classes:a.leading},o),Object(i.m)("div",{classes:a.title,key:"title"},d&&d)),Object(i.m)("div",{classes:a.secondary,key:"secondary"},Object(i.m)("nav",{classes:a.actions,key:"actions"},n&&(Array.isArray(n)?n:[n]).map(e=>Object(i.m)("div",{classes:a.action},e))),_&&Object(i.m)("div",{classes:a.trailing},_)))))});t.default=c},73:function(e,t,s){"use strict";s.d(t,"b",function(){return o});var r=s(5),a=s(75);const i=Object(r.a)({coreTheme:a.a});function c(e){return`${e.charAt(0).toUpperCase()}${e.slice(1)}`}function n(e){return e&&e.hasOwnProperty("variant")}const o=i(function({middleware:{coreTheme:e},properties:t}){return Object.assign({compose:(s,r,a)=>{const i=t().theme,o=s[" _key"],d=r[" _key"],_=Object.keys(s).reduce((e,t)=>" _key"===t?e:(a&&!e[`${a}${c(t)}`]&&(e[`${a}${c(t)}`]=" "),r[t]||(e[t]=" "),e),{" _key":d}),m=e.classes(_),l=e.classes(r);let h=e.classes(s);if(a){const e=Object.keys(Object.assign({},m,l)).reduce((e,t)=>{if(0===t.indexOf(a)&&t!==a){const s=function(e){return`${e.charAt(0).toLowerCase()}${e.slice(1)}`}(t.replace(a,""));!l[t]&&m[t]&&m[t].trim()&&(e[s]=`${h[s]} ${m[t].trim()}`),l[t]&&(e[s]=l[t])}return e},{});return h=Object.assign({},h,e),n(i)?{theme:{theme:Object.assign({},i.theme.theme,{[o]:h}),variants:i.theme.variants},variant:i.variant}:Object.assign({},i,{[o]:h})}const u=Object.keys(h).reduce((e,t)=>{if(" _key"===t)return e;const s=l[t]&&l[t].trim();return l[t]?e[t]=s:m[t]&&m[t].trim()&&(e[t]=`${e[t]} ${m[t].trim()}`),e},Object.assign({},h));return n(i)?{theme:{theme:Object.assign({},i.theme.theme,{[o]:u}),variants:i.theme.variants},variant:i.variant}:Object.assign({},i,{[o]:u})}},e)});t.a=o}}]);
//# sourceMappingURL=49-7.0.0-pre.js.map