/*!
 * 
 * [Dojo](https://dojo.io/)
 * Copyright [JS Foundation](https://js.foundation/) & contributors
 * [New BSD license](https://github.com/dojo/meta/blob/master/LICENSE)
 * All rights reserved
 * 
 */
(window.dojoWebpackJsonpdojo_widgets_custom_elements=window.dojoWebpackJsonpdojo_widgets_custom_elements||[]).push([[50],{25:function(e,t,r){"use strict";r.r(t),r.d(t,"LoadingIndicator",function(){return a});var n=r(91),s=r(73),i=r(5);const a=Object(i.a)({theme:s.a}).properties()(function({middleware:{theme:e}}){const t=e.classes(n);return Object(i.m)("div",{classes:[e.variant(),t.root],role:"progressbar"},Object(i.m)("div",{classes:t.buffer}),Object(i.m)("div",{classes:[t.bar,t.primary]},Object(i.m)("span",{classes:t.inner})))});t.default=a},73:function(e,t,r){"use strict";r.d(t,"b",function(){return c});var n=r(5),s=r(75);const i=Object(n.a)({coreTheme:s.a});function a(e){return`${e.charAt(0).toUpperCase()}${e.slice(1)}`}function o(e){return e&&e.hasOwnProperty("variant")}const c=i(function({middleware:{coreTheme:e},properties:t}){return Object.assign({compose:(r,n,s)=>{const i=t().theme,c=r[" _key"],m=n[" _key"],d=Object.keys(r).reduce((e,t)=>" _key"===t?e:(s&&!e[`${s}${a(t)}`]&&(e[`${s}${a(t)}`]=" "),n[t]||(e[t]=" "),e),{" _key":m}),u=e.classes(d),_=e.classes(n);let b=e.classes(r);if(s){const e=Object.keys(Object.assign({},u,_)).reduce((e,t)=>{if(0===t.indexOf(s)&&t!==s){const r=function(e){return`${e.charAt(0).toLowerCase()}${e.slice(1)}`}(t.replace(s,""));!_[t]&&u[t]&&u[t].trim()&&(e[r]=`${b[r]} ${u[t].trim()}`),_[t]&&(e[r]=_[t])}return e},{});return b=Object.assign({},b,e),o(i)?{theme:{theme:Object.assign({},i.theme.theme,{[c]:b}),variants:i.theme.variants},variant:i.variant}:Object.assign({},i,{[c]:b})}const l=Object.keys(b).reduce((e,t)=>{if(" _key"===t)return e;const r=_[t]&&_[t].trim();return _[t]?e[t]=r:u[t]&&u[t].trim()&&(e[t]=`${e[t]} ${u[t].trim()}`),e},Object.assign({},b));return o(i)?{theme:{theme:Object.assign({},i.theme.theme,{[c]:l}),variants:i.theme.variants},variant:i.variant}:Object.assign({},i,{[c]:l})}},e)});t.a=c},91:function(e,t,r){e.exports={" _key":"@dojo/widgets/loading-indicator",root:"loading-indicator-m__root__3zBTf",buffer:"loading-indicator-m__buffer__qJrL-",bar:"loading-indicator-m__bar__2o6JH",primary:"loading-indicator-m__primary__SBqVC",inner:"loading-indicator-m__inner__212NS"}}}]);
//# sourceMappingURL=50-7.0.0-pre.js.map